[package]
name = "bench_sum"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
tfhe = { path = "../../", features = ["integer", "nightly-avx512"] }

[features]
default = []
gpu = ["tfhe/gpu"]

[profile.release]
lto = "fat"
