[workspace]
resolver = "2"
members = [
    "crates/*",
    "tasks",
    "apps/trivium",
    "backends/tfhe-cuda-backend",
]

exclude = [
    "crates/tfhe/backward_compatibility_tests",
    "utils/cargo-tfhe-lints-inner",
    "utils/cargo-tfhe-lints"
]

[workspace.dependencies]
aligned-vec = { version = "0.5", default-features = false }
bytemuck = "1.14.3"
dyn-stack = { version = "0.10", default-features = false }
num-complex = "0.4"
pulp = { version = "0.18.22", default-features = false }
serde = { version = "1.0", default-features = false }
wasm-bindgen = ">=0.2.86,<0.2.94"

[workspace.package]
version = "0.11.0"
license = "BSD-3-Clause-Clear"
repository = "https://github.com/zama-ai/tfhe-rs"
documentation = "https://docs.zama.ai/tfhe-rs"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(bench)',
    'cfg(tarpaulin)',
    'cfg(tfhe_lints)',
] }

[profile.bench]
lto = "fat"

[profile.release]
lto = "fat"

[profile.release_lto_off]
inherits = "release"
lto = "off"

# Compiles much faster for tests and allows reasonable performance for iterating
[profile.devo]
inherits = "dev"
opt-level = 3
lto = "off"
debug-assertions = false
