 
[fpga]
  regmap="backends/tfhe-hpu-backend/config/hpu_regif_core.toml"
  polling_us=10
[fpga.ffi.Sim]
pbs_params = {lwe_dimension = 724, glwe_dimension = 2, polynomial_size = 1024, lwe_modular_std_dev = 1.2597809688976277e-5, glwe_modular_std_dev = 2.2737367544323206e-13, pbs_base_log = 20, pbs_level = 1, ks_base_log = 2, ks_level = 7, message_width = 2, carry_width = 2, ciphertext_width = 44}
ntt_params = {core_arch =  "WmmUnfoldPcg", batch_pbs_nb =  16, total_pbs_nb =  32, ct_width =  44, radix =  2, stg_nb =  10, prime_modulus =  17592186028033, psi =  16, delta =  5 }
ks_params =  {width =  21, lbx =  2, lby =  32, lbz =  3}
pc_params = {ksk_pc= 4,bsk_pc= 4,pem_pc= 2}
regf_params = {reg_nb= 64, coef_nb= 32}
isc_params = {min_iop_size = 4}
isc_sim_params = {reg_nb = 64, isc_depth = 64, alu_cfg ="backends/tfhe-hpu-backend/config/alu_cfg/hpu_coefs32.ron", freq_MHz= 250}

[rtl]
  bpip_used = true
  bpip_timeout = 100_000

[board]
  ct_bank = [4096, 0, 0, 4096]
  ct_pc = [10, 11]

  lut_bank = 256
  lut_pc = 12

  fw_size= 65536
  fw_pc = 1

  bsk_pc = [ 2, 3, 4, 5, 6, 7, 8, 9]
  ksk_pc = [24,25,26,27,28,29,30,31]

[firmware]
  integer_w=[16]
  pbs_w=8
  custom_iop.CUST_0 = "backends/tfhe-hpu-backend/config/custom_iop/cust_0.asm"
  custom_iop.CUST_1 = "backends/tfhe-hpu-backend/config/custom_iop/cust_1.asm"
  custom_iop.CUST_2 = "backends/tfhe-hpu-backend/config/custom_iop/cust_2.asm"
